### ISSUE TITLE
Cannot save test. TypeError: Preferences.getString is not a function

### ISSUE THREAD

**Issue by terovuorenmaa** [SeleniumBuilder/se-builder#262]
After updating Firefox to 38.0.1 the save is not working. gives TypeError: Preferences.getString is not a function

**Comment by Zarkonnen** [comment]
If you update to Builder 2.3.3 this should be fixed. Let me know if it isn't.

**Comment by Zarkonnen** [comment]
Assumed fixed.

**Comment by terovuorenmaa** [comment]
Still haven’t time to verify is build 2.3.3. fix the problem.

BTW: should I get the latest build by downloading it from http://saucelabs/builder? I did have time to reinstall the builder from there and that didn’t fix the problem. Didn’t have though to reinvestigate more than that. :(

**Comment by Zarkonnen** [comment]
It *should* auto-update, but failing that, use the version from 
http://sebuilder.com

**Comment by NicolasTr** [comment]
@Zarkonnen I had the same issue. Updating to 2.3.3 fixed it. The not up to date version came from https://saucelabs.com/builder

**Comment by terovuorenmaa** [comment]
Same here. Thanks.

Lähetetty Windows Phonesta
________________________________
Lähettäjä: Nicolas Trésegnie<mailto:notifications@github.com>
Lähetetty: ‎27.‎5.‎2015 2:02
Vastaanottaja: SeleniumBuilder/se-builder<mailto:se-builder@noreply.github.com>
Kopio: terovuorenmaa<mailto:terov@live.com>
Aihe: Re: [se-builder] Cannot save test. TypeError: Preferences.getString is not a function (#262)

@Zarkonnen I had the same issue. Updating to 2.3.3 fixed it. The not up to date version came from https://saucelabs.com/builder

---

**Comment by Dev2016** [comment]
Me to got the same Typeerror:Preferences:getString is not a function. Even i tried to saucelabs.com but they got the outdated version. After updating through sebuilder.com then the same got fixed. Thanks to Zarkonnen for the solution.

**Comment by grugnog** [comment]
@Zarkonnen I still had this issue using the version from https://saucelabs.com/builder

**Comment by Zarkonnen** [comment]
Yeah, the one on saucelabs.com is outdated. I need to poke them about this. :) Use this one: http://seleniumbuilder.github.io/se-builder/selenium-builder-latest.xpi
